import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
const data=mkdtempSync(path.join(tmpdir(),'plantmeet-test-'));
let child;
async function start(){child=spawn(process.execPath,['server.mjs'],{cwd:import.meta.dirname,env:{...process.env,PORT:'4175',PLANTMEET_DATA:data},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{child.stdout.on('data',d=>{if(d.toString().includes('PlantMeet:'))resolve()});child.on('error',reject);child.on('exit',c=>{if(c)reject(Error('Server exit '+c))});setTimeout(()=>reject(Error('Server timeout')),8000).unref()});}
async function stop(){if(!child)return;await new Promise(resolve=>{child.once('exit',resolve);child.kill()});}
const req=async(p,b)=>{const r=await fetch('http://localhost:4175/api/'+p,b===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return {status:r.status,data:await r.json()}};
test('PlantMeet: persistence, attendance, validation, expiry and protection',async t=>{await start();t.after(stop);
 const state=(await req('state')).data;assert.equal(state.roster.length,12);assert.equal(state.lessons.length,10);assert.equal(state.profile.name,'Арайлым');assert.ok(state.lessons.every(l=>l.duration===(l.kind==='Лекция'?50:90)));assert.equal(new Set(state.lessons.map(l=>l.title)).size,5);
 assert.equal((await req('join',{lesson_id:'missing'})).status,400);
 const s=(await req('join',{lesson_id:'1'})).data;assert.ok(s.id);
 assert.equal((await req('participants',{id:s.id,name:state.roster[1]})).status,200);
 assert.equal((await req('participants',{id:s.id,name:state.roster[1]})).status,200);
 assert.equal((await req('participants',{id:s.id,name:'invalid'})).status,400);
 assert.equal((await req('messages',{id:s.id,text:'   '})).status,400);
 assert.equal((await req('messages',{id:s.id,text:'Тестовое сообщение'})).status,201);
 assert.equal((await req('messages?id='+s.id)).data[0].text,'Тестовое сообщение');
 assert.equal((await req('profile',{name:'Тест',email:'invalid',group_name:'ИС-302',program:'ИС'})).status,404);
 assert.equal((await req('lessons',{title:'',teacher:'Тест',date:'2026-10-03',time:'10:00',duration:60,kind:'Лекция'})).status,400);
 assert.equal((await req('lessons',{title:'Тест',teacher:'Тест',date:'2026-10-03',time:'99:99',duration:60,kind:'Лекция'})).status,400);
 assert.equal((await req('lessons',{title:'Тест',teacher:'Тест',date:'2026-10-03',time:'10:00',duration:60,kind:'Лекция'})).status,201);assert.equal((await req('state')).data.lessons.find(l=>l.title==='Тест').duration,50);
 const before=(await req('attendance?id='+s.id)).data;assert.equal(before.filter(x=>x.joined).length,2);assert.equal(before.length,12);
 assert.equal((await req('leave',{id:s.id})).status,200);assert.equal((await req('leave',{id:s.id})).status,200);
 const after=(await req('attendance?id='+s.id)).data;assert.equal(after.filter(x=>x.joined&&x.left_at).length,2);assert.equal(after.filter(x=>!x.joined).length,10);
 assert.equal((await req('messages',{id:s.id,text:'После выхода'})).status,400);
 assert.equal((await req('participants',{id:s.id,name:state.roster[2]})).status,400);
 const upload=await fetch('http://localhost:4175/api/recordings?session='+s.id,{method:'POST',body:Buffer.from([0x1a,0x45,0xdf,0xa3,0,1,2,3])});assert.equal(upload.status,201);
 const recording=(await req('state')).data.recordings[0];const created=new Date(recording.created),expires=new Date(recording.expires);assert.equal(expires.getMonth(),(created.getMonth()+1)%12);
 const range=await fetch('http://localhost:4175/recordings/'+recording.filename,{headers:{Range:'bytes=0-3'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,4);
 const deleted=await req('recordings/delete',{id:recording.id});assert.equal(deleted.status,200);
 assert.equal(existsSync(path.join(data,'recordings',recording.filename)),false);
 assert.equal((await req('state')).data.recordings.length,0);
 assert.equal((await req('recordings/delete',{id:recording.id})).status,404);
 assert.equal((await req('attendance?id='+s.id)).data.length,12);
 const replacement=await fetch('http://localhost:4175/api/recordings?session='+s.id,{method:'POST',body:Buffer.from([0x1a,0x45,0xdf,0xa3,0,1,2,3])});assert.equal(replacement.status,201);
 const denied=await fetch('http://localhost:4175/api/leave',{method:'POST',headers:{Origin:'https://example.com','Content-Type':'application/json'},body:JSON.stringify({id:s.id})});assert.equal(denied.status,403);
 await stop();const db=new DatabaseSync(path.join(data,'plantmeet.sqlite'));db.prepare('UPDATE recordings SET expires=?').run(Date.now()-1000);db.prepare('UPDATE profile SET name=?').run('Арайлым Женискызы');db.prepare('UPDATE attendance SET student=? WHERE student=?').run('Арайлым Женискызы','Арайлым');db.prepare('DELETE FROM migrations WHERE name=?').run('subjects-and-name-v2');db.close();await start();
 const restored=(await req('state')).data;assert.equal(restored.sessions.length,1);assert.equal(restored.profile.name,'Арайлым');assert.equal((await req('attendance?id='+s.id)).data.some(a=>a.student==='Арайлым'),true);assert.ok(restored.sessions[0].ended);assert.equal(restored.recordings.length,0);assert.equal(restored.lessons.length,11);
 assert.equal((await req('attendance?id='+s.id)).data.length,12);
});
